version: '2' 
services:
  order:
     container_name: order-service
     image:   robert0714/order-service:ch08
     network_mode:  "host"
     environment:
         server.port: "8090"
         eureka.client.enabled: "false"
         eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
         spring.boot.admin.url: http://localhost:8181/sba
         spring.cloud.discovery.enabled: "false"
         spring.cloud.config.server.encrypt.enabled: "false"
         TZ: Asia/Taipei
  account:
     container_name: account-service
     image:  robert0714/account-service:ch08
     network_mode:  "host"
     environment:
         server.port: "8091"
         eureka.client.enabled: "false"
         eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
         spring.boot.admin.url: http://localhost:8181/sba
         spring.cloud.discovery.enabled: "false"
         spring.cloud.config.server.encrypt.enabled: "false"
         TZ: Asia/Taipei
  customer:
     container_name: customer-service
     image:  robert0714/customer-service:ch08
     network_mode:  "host"
     environment:
         server.port: "8092"
         eureka.client.enabled: "false"
         eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
         spring.boot.admin.url: http://localhost:8181/sba
         spring.cloud.discovery.enabled: "false"
         spring.cloud.config.server.encrypt.enabled: "false"
         TZ: Asia/Taipei
  product:
     container_name: product-service
     image:  robert0714/product-service:ch08
     network_mode:  "host"
     environment:
         server.port: "8093"
         eureka.client.enabled: "false"
         eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
         spring.boot.admin.url: http://localhost:8181/sba
         spring.cloud.discovery.enabled: "false"
         spring.cloud.config.server.encrypt.enabled: "false"
         TZ: Asia/Taipei
  gateway:
     container_name: gateway-service
     image:  robert0714/gateway-service:ch08
     network_mode:  "host"
     environment:
         server.port: "8080"
         eureka.client.enabled: "false"
         eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
         spring.boot.admin.url: http://localhost:8181/sba
         spring.cloud.discovery.enabled: "false"
         spring.cloud.config.server.encrypt.enabled: "false"
         TZ: Asia/Taipei
        